### ISSUE TITLE
Chat linking broken

### ISSUE THREAD

**Issue by Malivil** [exochron/MountJournalEnhanced#101]
When I try to link a mount from the journal to chat (open chat, Shift+Click mount in journal) it creates an incomplete link like this: ```|Hmount:368896:107058:IIqIVlIIrIWNIIsIWeIItIWrIIuLNyIIwLPOIIxIXZIIyIXaIP\LOsIV\KxPIWWLMTIWYLMkIW]LNPIWaLNdIWbLNlIWcLNrIWeLO]IZkKbmIZuKoSI[MLssI[eKpXI[oKpmI[yKqJIhePdWIhfPdUIhgPdeIhhPd\IhiPdgIhjPd]IhkPdpIhlPd`IhuPfQIhwPfkIhxPfnIhyPfrIhzPftIh{PfyIiIPgMIiJPg```

This creates a blank message when I send it.

I am using Prat so I'm wondering if there is an incompatibility there, but I haven't tried without it.
EDIT: Just tried without prat and it's still happening

**Comment by Malivil** [comment]
Not sure what changed but this is working again

**Comment by exochron** [comment]
Thank you for reporting this.
I can replicate this bug and it seems, that it's coming from the blizzard UI itself :(
I think the chat input allows only ~256 characters. But mount links are now over 1000 characters long. (although shown differently)
Maybe I can whip up a workaround :)

**Comment by exochron** [comment]
Alright no need for that. That issue is already fixed on PTR 10.2.5. So just wait a few more days. :wink: 
I keep this issue open just to make sure, when the patch goes live.

On 10.2.0 (currently still live) the function C_MountJournal.GetMountLink( ) returns a lot of gibberish data, which seems even cut off after 1023 letters. So the trailing escape sequence of a hyperlink is missing. Therefore it can not be parsed and results in gibberish text in the chat editbox. The editbox is also limited to 255 letters. So the text gets cut off even more.

**Comment by Malivil** [comment]
Hm, interesting that it works sometimes. Definitely speaks to it being a bug on Blizzard's side =)

Thanks for looking into it!

**Comment by exochron** [comment]
... and its still on live (10.2.5) :disappointed:

**Comment by elvanna** [comment]
Hi I have the same issue still going on, I can link the mount to chat and show it using a different mount journal addon which I had to switch to because it wasnt working with this one, but I love this one and want to use it again. there addon allows for linking to chat, but I did find this on redit just now, that if you add " local o=C_MountJournal.GetMountLink function C_MountJournal.GetMountLink(id) local p=o(id) local a,b,c = p:match("(|cff71d5ff|Hmount:%d+:%d+:)(.+)(|h%[.+%]|h|r)") return a.."x"..c end" that should fix it, but I would have no idea where in the addon to put this.

They also had this as a /run or macro "/run local o=C_MountJournal.GetMountLink function C_MountJournal.GetMountLink(id) local p=o(id) local a,b,c = p:match("(\124cff71d5ff\124Hmount:%d+:%d+:)(.+)(\124h%[.+%]\124h\124r)") return a.."x"..c end" which does allow to link mounts while using the addon but if you reload it stops working, so I hope this might help in some form as i want to come back to using your addon.

by the way the other addon that chat linking works with is mountsjournal if that helps with also fixing the issue.

**Comment by exochron** [comment]
Thank you @elvanna for the tip.
I got a little fix for the next version. It should work for most cases. Although it's not perfect yet.
Newer dragonflight mounts could add more parameters to the hyperlink. So you can show your unique mount setup in the chat. (similar to wardrobe links) Well, that doesn't work yet :-/

**Comment by elvanna** [comment]
@exochron No porblem at all, I shall await the new updated with baited breath :)

**Comment by exochron** [comment]
just released in version 2.33.0 :smile:

**Comment by elvanna** [comment]
I saw :)

**Comment by elvanna** [comment]
@exochron still not letting me link mounts to chat :(

**Comment by exochron** [comment]
@elvanna Are you using retail or wotlk?
as far as I know it's not possible yet in classic to link mounts or pets (without addons).

The current fix is just for Retail where the chatbox gets filled with a lot of random chars.

**Comment by elvanna** [comment]
@exochron I am in retail, the chat linking works on soome of my toons but not others and it is also without any addons on it wont link either. so it isnt just your addon I can't link with but like i said before suing the addon monutsjournal, which I hate the ui for allows me on every toon to link mounts to chat, so I don't what they are doing to allow it.

**Comment by elvanna** [comment]
@exochron have just tried with bug sack and grabber, if i try to link with the addon I get an error nose from them, but nothing to show the error to be able to send over the box is just blank, was hoping i could get something else to help out. :(

**Comment by exochron** [comment]
Hi @elvanna, I've just released version [2.33.1](https://github.com/exochron/MountJournalEnhanced/releases/tag/2.33.1) . It includes some minor changes regarding linking mounts. Please give it a try. It might already solve your issue.

**Comment by elvanna** [comment]
Hi @exochron WE HAVE A WINNER I have been offline all day and only just got online, I have just tested and mounts are now linking, thank you so much for working on this you are a true star of a dev :)

**Comment by exochron** [comment]
Thank you for your kind word and for staying until this has been fixed :hugs:
